# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = cn.ksmcbrigade.rd_mcmod_sp
archives_base_name = MCModSplashesRd
mod_name =  MCMod Splashes Rd-132211
mod_id = mcmod_sp
mod_description=Nothing
mod_license=CC0-1.0
mod_authors=commonplace

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = a1.0.1_01
loader_version = 0.17.3

feather_build = 26
